### ISSUE TITLE
Some usability improvements

### ISSUE THREAD

**Issue by ramiropolla** [pawelzwronek/LiveMosher#2]
Hi,

I've finally had the time to test a bit more, and I have some usability suggestions:
- It would be nice to curate the scripts. Some require midi, others are too old and just don't work. This would be important for a first release so that it "just works", even if with limited scripts.
- When copying the scripts to "My moshers", it doesn't copy the dependencies (like `helpers.mjs`). We should find a way so that it works out of the box. I don't know what would be the best approach though.
- Maybe add a `loop` toggle button so that the video keeps looping around (I found it useful when dealing with short clips), not high priority.
- It seems the input file is transcoded in every run (before being glitched). It could speed things up if the transcoded file is cached (when no parameters are changed). This is low priority though, it doesn't need to block a first release.

And congratulations, it's a great front-end which will surely help with the adoption of ffglitch!
There's no need to setup complicated editors or IDEs or deal with the command line, which is a high barrier for most users.

Thanks,
Ramiro

**Comment by pawelzwronek** [comment]
>     * It would be nice to curate the scripts. Some require midi, others are too old and just don't work. This would be important for a first release so that it "just works", even if with limited scripts.

Yep. Need to review all the scrips. They are untouched copy from the repo.
 
>     * When copying the scripts to "My moshers", it doesn't copy the dependencies (like `helpers.mjs`). We should find a way so that it works out of the box. I don't know what would be the best approach though.

Yep. I was thinking about it couple of times. My best solution is to find imported libs inside the main script and recursevly in all imported scripts and copy them and keep their folders structure.

>     * Maybe add a `loop` toggle button so that the video keeps looping around (I found it useful when dealing with short clips), not high priority.

Good idea. For that I will add an end marker (similar to `Set restart time`) and a `Loop` button/checkbox.

>     * It seems the input file is transcoded in every run (before being glitched). It could speed things up if the transcoded file is cached (when no parameters are changed). This is low priority though, it doesn't need to block a first release.

Caching transcoded content, especially on large files and when you seek the file at random position can be challenging and also disk space consuming task. Moreover transcoding takes about 4th or less part of the main recording encoding a cpu usage, so I would leave it like it is now. However on a low end desktops it may be beneficial 🤔

> And congratulations, it's a great front-end which will surely help with the adoption of ffglitch! There's no need to setup complicated editors or IDEs or deal with the command line, which is a high barrier for most users.

Thanks.

**Comment by pawelzwronek** [comment]
Just finished fixing all the issues @ramiropolla 
1. Fixed most of the scripts, removed `fflive_pipe.sh` and `file_to_mpeg4.sh`, added one `midi.js` with support for MIDI emulation over ZMQ (see 5.), changed some names.

  Two notes:
  - `mv_producer.js`, not sure why this error
```
const data = fwd_mvs.serialize(); 
00:00.28: [quickjs] TypeError: not a function
00:00.28: [quickjs]     at glitch_frame (c:/DEVEL/python/LiveMosher/Examples/zmq-demo/mv_producer.js:27)
```
  - Not sure how `pixelsort_gbrp-midi.js` works

2. Now when editing some script, all included libraries are copied too.
3. Added 2nd marker:  'End marker' and when you start playing inside the markers looping takes place inside the markers. Looping is enabled always now.
4. Added support for `vf_script` using only fflive. No ffgac transcoding is done, see an example `uv.js`.
5. Added a virtual MIDI piano to support MIDI scripts when no MIDI device is available:
![obraz](https://github.com/user-attachments/assets/3cfec4b9-91e1-4521-be07-6167094b40e3)
6. Deleted scripts are send to trash.
7. Added 'Running from source' chapter to `README.md`

**Comment by ramiropolla** [comment]
> Just finished fixing all the issues @ramiropolla
> 
> 1. Fixed most of the scripts, removed `fflive_pipe.sh` and `file_to_mpeg4.sh`, added one `midi.js` with support for MIDI emulation over ZMQ (see 5.), changed some names.
> 
> Two notes:
> 
> * `mv_producer.js`, not sure why this error
> 
> ```
> const data = fwd_mvs.serialize(); 
> 00:00.28: [quickjs] TypeError: not a function
> 00:00.28: [quickjs]     at glitch_frame (c:/DEVEL/python/LiveMosher/Examples/zmq-demo/mv_producer.js:27)
> ```

The `serialize()` function was removed in favour of `toUint8FFArray()`. But it seems I don't have any examples of how to use it (oops). The `mv_server` could be removed for now.

> * Not sure how `pixelsort_gbrp-midi.js` works

It could be removed for now as well, until we have time to properly test it.

> 2. Now when editing some script, all included libraries are copied too.
> 3. Added 2nd marker:  'End marker' and when you start playing inside the markers looping takes place inside the markers. Looping is enabled always now.
> 4. Added support for `vf_script` using only fflive. No ffgac transcoding is done, see an example `uv.js`.

Nice!

> 5. Added a virtual MIDI piano to support MIDI scripts when no MIDI device is available:
>    ![obraz](https://private-user-images.githubusercontent.com/23583498/395820370-3cfec4b9-91e1-4521-be07-6167094b40e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDM0MjUsIm5iZiI6MTczNDQwMzEyNSwicGF0aCI6Ii8yMzU4MzQ5OC8zOTU4MjAzNzAtM2NmZWM0YjktOTFlMS00NTIxLWJlMDctNjE2NzA5NGI0MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAyMzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MWViNTFhNDk4Y2UwMWI5YjljNzhmNDE1Njg5OTRjMjgwMWU5MTI0Nzg3NDMwNDQ4NDVlYjA4NTQxNGYzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PZgY18DNeg6dy7Ct_vI2LgXs9cT9-Jc3pzXH0FPQ-2s)

Wow!!! This is truly amazing. It seems to be hardcoded to Windows though (`RtMidi.WINDOWS_MM`, and `count === 0`, whereas Linux always has at least one default `Midi Through` port). The vast majority of users will be using Windows though.

> 6. Deleted scripts are send to trash.
> 7. Added 'Running from source' chapter to `README.md`

Another couple of issues I came across:
- In `basic-keyboard`, could you add `frame.mv.overflow = "truncate";`?
- When I reposition the `fflive` window and the video loops, the position is reset. I see there is already code to set the window position, but this doesn't seem to be respected in this case.
- Could you add a help or about dialog or something similar that points to the issues page here where users can report issues?

Even without addressing these little issues, I think it's ready for a first non-alpha release. Then I can add it to the frontends page and announce it. Do you want to write a post for https://github.com/ramiropolla/ffglitch.org or would you rather I do it?

Thank you for your hard work. I'm looking forward to seeing more people using it!

**Comment by pawelzwronek** [comment]
> The `serialize()` function was removed in favour of `toUint8FFArray()`. But it seems I don't have any examples of how to use it (oops). The `mv_server` could be removed for now.

Changed `serialize()` to `toUint8FFArray()` and kept `zmq-demo/mv_producer.js` as a reference for sending over ZMQ Push.

> It seems to be hardcoded to Windows though (`RtMidi.WINDOWS_MM`, and `count === 0`, whereas Linux always has at least one default `Midi Through` port). The vast majority of users will be using Windows though.

Changed `rtmidi.WINDOWS_MM` to `rtmidi.UNSPECIFIED` and fallback to ZMQ when `port_num == undefined` to fix linux issue.

> In `basic-keyboard`, could you add `frame.mv.overflow = "truncate";`?

Done.

> When I reposition the `fflive` window and the video loops, the position is reset. I see there is already code to set the window position, but this doesn't seem to be respected in this case.

This issue is tricky, because I'm unable to reproduce it on any of my real (Windows10) and virtual (Ubuntu and macOS) hosts :(

> Could you add a help or about dialog or something similar that points to the issues page here where users can report issues?

![obraz](https://github.com/user-attachments/assets/1dadc282-7412-4c53-9c00-761f8770887f)

Also added a 'Share' button that bundle the script and the related imports to one .zip file and open [show-and-tell](https://github.com/pawelzwronek/LiveMosher/discussions/categories/show-and-tell) url. Soon I'll post an example to 'show-and-tell' discussion.
![obraz](https://github.com/user-attachments/assets/865431aa-8484-43e9-bd1f-c102dfc6e0c6)

Removed hardcoded scaling of input video to 1280x720.
Also I had to transcode an input video when a filter script is used for accurate seeking, `fflive` seems not support `-accurate_seek`.

> Even without addressing these little issues, I think it's ready for a first non-alpha release. Then I can add it to the frontends page and announce it. Do you want to write a post for https://github.com/ramiropolla/ffglitch.org or would you rather I do it?

Great. If you have no further issues, I will change the version to 1.0, prepare the bundles and publish then on github. I'll ping you in this post when done.
Feel free to create the post :)

> Thank you for your hard work. I'm looking forward to seeing more people using it!

The pleasure is all mine.

**Comment by ramiropolla** [comment]
- Could you also add an about or credits link/dialog anywhere that points to the project website? `Report an issue` is useful, but having a direct link to the project website might also help (some people might not remember where the program came from).

- Could you create a high resolution image (at least 512x512) to be used as the post image (and the instagram image as well)? It could even be just the program icon, but in higher resolution.

- Also, for a real name in the post and front-ends page, is `Paweł Zwronek` correct? (sorry my Polish is not good :P)

**Comment by pawelzwronek** [comment]
> * Could you also add an about or credits link/dialog anywhere that points to the project website? `Report an issue` is useful, but having a direct link to the project website might also help (some people might not remember where the program came from).

![obraz](https://github.com/user-attachments/assets/66032d18-b086-48ad-8781-a9ebfa2dae13)
Do you think I should add somebody else?

> 
>     * Could you create a high resolution image (at least 512x512) to be used as the post image (and the instagram image as well)? It could even be just the program icon, but in higher resolution.

Here you go:
![500x500_1](https://github.com/user-attachments/assets/1df6c772-c059-46fe-bfaa-7127ac2ebf1e)


>     * Also, for a real name in the post and front-ends page, is `Paweł Zwronek` correct? (sorry my Polish is not good :P)

`pawelzwronek` is fine. Out of curiosity how did you find out I'm from Poland? :)

**Comment by ramiropolla** [comment]
> > * Could you also add an about or credits link/dialog anywhere that points to the project website? `Report an issue` is useful, but having a direct link to the project website might also help (some people might not remember where the program came from).
> 
> ![obraz](https://github.com/user-attachments/assets/66032d18-b086-48ad-8781-a9ebfa2dae13)
> Do you think I should add somebody else?

This should be ok.

> >     * Could you create a high resolution image (at least 512x512) to be used as the post image (and the instagram image as well)? It could even be just the program icon, but in higher resolution.
> 
> Here you go:
> ![500x500_1](https://github.com/user-attachments/assets/1df6c772-c059-46fe-bfaa-7127ac2ebf1e)

Thanks!

> >     * Also, for a real name in the post and front-ends page, is `Paweł Zwronek` correct? (sorry my Polish is not good :P)
> 
> `pawelzwronek` is fine. Out of curiosity how did you find out I'm from Poland? :)

The username looks Polish, but I also asked ChatGPT :P.

Do you think you can make the new release soon enough so that people have time to play with it during this week of holidays?

**Comment by pawelzwronek** [comment]
> The username looks Polish, but I also asked ChatGPT :P.

I see 😀

> Do you think you can make the new release soon enough so that people have time to play with it during this week of holidays?

Yeah, I think in a few hours I'll release v1.0.

**Comment by pawelzwronek** [comment]
@ramiropolla [v1.0](https://github.com/pawelzwronek/LiveMosher/releases/tag/1.0) is released.  Thanks for all the suggestions! Hope people will like the app.

Merry Christmas and Happy New Year to you 🤶

**Comment by ramiropolla** [comment]
https://ffglitch.org/2024/12/live_mosher_1_0.html
https://www.instagram.com/p/DD8dEy1gHHM/
❤️

**Comment by pawelzwronek** [comment]
That's awesome, thx!
